### ISSUE TITLE
Remaining Bug Reports from GitLab

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/searents#4]
https://gitlab.com/dmtucker/searents/-/issues
- [ ] [Cached Scrapes should have a URL associated with them](https://gitlab.com/dmtucker/searents/-/issues/11)
- [ ] [Invalid filter patterns cause a crash](https://gitlab.com/dmtucker/searents/-/issues/14)
- [ ] [`fetch` seems to break `verify`](https://gitlab.com/dmtucker/searents/-/issues/16)
- [ ] [Properties with no data cause `show -g` to crash](https://gitlab.com/dmtucker/searents/-/issues/17)
